import { DurableObject } from "cloudflare:workers";
const V="0.1.0", OAI="https://api.openai.com/v1", CF="https://api.cloudflare.com", LIMIT=1000;

export class RelayState extends DurableObject{
 constructor(ctx,env){super(ctx,env);this.ctx.blockConcurrencyWhile(async()=>{this.ctx.storage.sql.exec("CREATE TABLE IF NOT EXISTS kv(k TEXT PRIMARY KEY,v TEXT NOT NULL);CREATE TABLE IF NOT EXISTS c(k TEXT PRIMARY KEY,n INTEGER NOT NULL)")})}
 async get(k){const r=this.ctx.storage.sql.exec("SELECT v FROM kv WHERE k=?",k).toArray()[0];return r?JSON.parse(r.v):null}
 async put(k,v){this.ctx.storage.sql.exec("INSERT INTO kv(k,v) VALUES(?,?) ON CONFLICT(k) DO UPDATE SET v=excluded.v",k,JSON.stringify(v));return true}
 async del(k){this.ctx.storage.sql.exec("DELETE FROM kv WHERE k=?",k);return true}
 async inc(k){this.ctx.storage.sql.exec("INSERT INTO c(k,n) VALUES(?,1) ON CONFLICT(k) DO UPDATE SET n=n+1",k);return this.ctx.storage.sql.exec("SELECT n FROM c WHERE k=?",k).one().n}
}
const J=(x,s=200,h={})=>new Response(JSON.stringify(x),{status:s,headers:{"content-type":"application/json;charset=utf-8","cache-control":"no-store","x-compatrelay-version":V,...h}});
const P=(title,body)=>new Response(`<!doctype html><meta name=viewport content="width=device-width"><title>${title} — CompatRelay</title><style>body{margin:0;background:#080b10;color:#edf4fa;font:16px/1.55 system-ui}main,nav,footer{max-width:1080px;margin:auto;padding:24px}nav{display:flex;justify-content:space-between;border-bottom:1px solid #223040}a{color:#8df0c8}h1{font-size:clamp(44px,7vw,78px);line-height:.98;letter-spacing:-.055em;max-width:900px}.lead{font-size:20px;color:#afbecb;max-width:760px}.g{display:grid;grid-template-columns:repeat(3,1fr);gap:15px;margin:35px 0}.c{border:1px solid #243142;background:#10161e;border-radius:15px;padding:22px}.c p{color:#9fb0be}.tag{color:#8df0c8;font:12px monospace}.code{padding:18px;border:1px solid #263344;background:#05070a;border-radius:12px;font:13px monospace;white-space:pre-wrap}@media(max-width:800px){.g{grid-template-columns:1fr}}</style><nav><b>CompatRelay</b><span><a href=/docs>Docs</a> · <a href=/supported>Bridges</a> · <a href=/pricing>Pricing</a> · <a href=/security>Security</a></span></nav><main>${body}</main><footer>CompatRelay ${V} · deterministic runtime compatibility</footer>`,{headers:{"content-type":"text/html;charset=utf-8","content-security-policy":"default-src 'none';style-src 'unsafe-inline';frame-ancestors 'none'"}});
const id=p=>`${p}_${crypto.randomUUID().replaceAll("-","")}`, now=()=>Math.floor(Date.now()/1000), month=()=>new Date().toISOString().slice(0,7);
async function hash(s){const b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(s));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join("")}
function auth(req){const h=new Headers();for(const k of ["authorization","content-type","openai-organization","openai-project","x-client-request-id"]){const v=req.headers.get(k);if(v)h.set(k,v)}return h}
async function body(req){const n=Number(req.headers.get("content-length")||0);if(n>1e6)throw Error("too_large");const t=await req.text();if(t.length>1e6)throw Error("too_large");return t?JSON.parse(t):{}}
async function up(url,init){const r=await fetch(url,init),t=await r.text();let d;try{d=t?JSON.parse(t):{}}catch{d={error:{message:t}}}return{r,d}}
const U=x=>J(x.d,x.r.status,{"x-compatrelay-upstream-status":String(x.r.status)});
function text(c){if(typeof c==="string")return c;if(!Array.isArray(c))return"";return c.map(x=>x?.text?.value??x?.text??"").filter(Boolean).join("\n")}
function tools(ts=[]){return ts.flatMap(t=>t.type==="function"&&t.function?[{type:"function",name:t.function.name,description:t.function.description,parameters:t.function.parameters}]:t.type==="file_search"?[{type:"file_search"}]:[])}
function legacyRun(r,rec,thread){const calls=(r.output||[]).filter(x=>x.type==="function_call").map(x=>({id:x.call_id||x.id,type:"function",function:{name:x.name,arguments:x.arguments||"{}"}}));let st=calls.length?"requires_action":(r.status||"queued");if(st==="incomplete")st="failed";return{id:rec.id,object:"thread.run",created_at:rec.created_at,thread_id:thread,assistant_id:rec.assistant_id,status:st,required_action:calls.length?{type:"submit_tool_outputs",submit_tool_outputs:{tool_calls:calls}}:null,last_error:r.error||null,model:r.model||rec.model,instructions:rec.instructions,tools:rec.legacy_tools,metadata:rec.metadata||{},usage:r.usage?{prompt_tokens:r.usage.input_tokens||0,completion_tokens:r.usage.output_tokens||0,total_tokens:r.usage.total_tokens||0}:null}}
async function stub(req,env){const k=req.headers.get("x-compatrelay-key")||"";if(!/^cr_[A-Za-z0-9_-]{20,}$/.test(k))return null;const s=env.STATE.getByName(`p:${await hash(k)}`);return await s.get("project")?s:null}

async function openai(req,path,s){const m=req.method,h=auth(req);if(!h.get("authorization"))return J({error:{message:"Missing provider Authorization header"}},401);
 if(path==="/assistants"&&m==="POST"){const b=await body(req),a={id:id("asst"),object:"assistant",created_at:now(),name:b.name||null,description:b.description||null,model:b.model,instructions:b.instructions||null,tools:b.tools||[],tool_resources:b.tool_resources||{},metadata:b.metadata||{}};await s.put(`a:${a.id}`,a);return J(a)}
 let q=path.match(/^\/assistants\/([^/]+)$/);if(q){const a=await s.get(`a:${q[1]}`);if(!a)return J({error:{message:"Assistant not found"}},404);if(m==="GET")return J(a);if(m==="DELETE"){await s.del(`a:${q[1]}`);return J({id:q[1],object:"assistant.deleted",deleted:true})}}
 if(path==="/threads"&&m==="POST"){const b=await body(req),items=(b.messages||[]).map(x=>({type:"message",role:x.role||"user",content:text(x.content)})),x=await up(`${OAI}/conversations`,{method:"POST",headers:h,body:JSON.stringify({items,metadata:b.metadata||{}})});if(!x.r.ok)return U(x);const t={id:id("thread"),conversation_id:x.d.id,created_at:now(),metadata:b.metadata||{}};await s.put(`t:${t.id}`,t);return J({id:t.id,object:"thread",created_at:t.created_at,metadata:t.metadata,tool_resources:{}})}
 q=path.match(/^\/threads\/([^/]+)\/messages$/);if(q){const t=await s.get(`t:${q[1]}`);if(!t)return J({error:{message:"Thread not found"}},404);if(m==="POST"){const b=await body(req),x=await up(`${OAI}/conversations/${t.conversation_id}/items`,{method:"POST",headers:h,body:JSON.stringify({items:[{type:"message",role:b.role||"user",content:text(b.content)}]})});if(!x.r.ok)return U(x);const z=Array.isArray(x.d.data)?x.d.data[0]:x.d;return J({id:z.id||id("msg"),object:"thread.message",created_at:now(),thread_id:t.id,role:b.role||"user",content:[{type:"text",text:{value:text(b.content),annotations:[]}}],attachments:[],metadata:b.metadata||{}})}}
 q=path.match(/^\/threads\/([^/]+)\/runs$/);if(q&&m==="POST"){const t=await s.get(`t:${q[1]}`),b=await body(req);if(!t)return J({error:{message:"Thread not found"}},404);const a=await s.get(`a:${b.assistant_id}`);if(!a)return J({error:{message:"Assistant not found"}},404);const rec={id:id("run"),created_at:now(),thread_id:t.id,assistant_id:a.id,model:b.model||a.model,instructions:b.instructions||a.instructions,legacy_tools:b.tools||a.tools||[],metadata:b.metadata||{}};const x=await up(`${OAI}/responses`,{method:"POST",headers:h,body:JSON.stringify({model:rec.model,conversation:t.conversation_id,instructions:rec.instructions||undefined,tools:tools(rec.legacy_tools),background:true,metadata:{compatrelay_run:rec.id}})});if(!x.r.ok)return U(x);rec.response_id=x.d.id;await s.put(`r:${rec.id}`,rec);return J(legacyRun(x.d,rec,t.id))}
 q=path.match(/^\/threads\/([^/]+)\/runs\/([^/]+)$/);if(q&&m==="GET"){const rec=await s.get(`r:${q[2]}`);if(!rec)return J({error:{message:"Run not found"}},404);const x=await up(`${OAI}/responses/${rec.response_id}`,{headers:h});return x.r.ok?J(legacyRun(x.d,rec,q[1])):U(x)}
 q=path.match(/^\/threads\/([^/]+)\/runs\/([^/]+)\/submit_tool_outputs$/);if(q&&m==="POST"){const rec=await s.get(`r:${q[2]}`),t=await s.get(`t:${q[1]}`),b=await body(req);if(!rec||!t)return J({error:{message:"Run not found"}},404);const input=(b.tool_outputs||[]).map(x=>({type:"function_call_output",call_id:x.tool_call_id,output:String(x.output??"")}));const x=await up(`${OAI}/responses`,{method:"POST",headers:h,body:JSON.stringify({model:rec.model,conversation:t.conversation_id,input,instructions:rec.instructions||undefined,tools:tools(rec.legacy_tools),background:true})});if(!x.r.ok)return U(x);rec.response_id=x.d.id;await s.put(`r:${rec.id}`,rec);return J(legacyRun(x.d,rec,t.id))}
 const target=new URL(`${OAI}${path}`),i=new URL(req.url);target.search=i.search;const init={method:m,headers:h,redirect:"manual"};if(!["GET","HEAD"].includes(m))init.body=req.body;const r=await fetch(target,init);const oh=new Headers(r.headers);oh.set("x-compatrelay-version",V);return new Response(r.body,{status:r.status,headers:oh})}

async function cloudflare(req,path){const h=auth(req);if(!h.get("authorization"))return J({success:false,errors:[{message:"Missing provider Authorization header"}]},401);const mapped=path.replace(/^\/client\/v4\/accounts\/([^/]+)\/workers\/namespaces(?=\/|$)/,"/client/v4/accounts/$1/storage/kv/namespaces"),u=new URL(`${CF}${mapped}`),i=new URL(req.url);u.search=i.search;const init={method:req.method,headers:h,redirect:"manual"};if(!["GET","HEAD"].includes(req.method))init.body=req.body;const r=await fetch(u,init),oh=new Headers(r.headers);oh.set("x-compatrelay-bridge",mapped===path?"pass-through":"cf-kv-legacy");return new Response(r.body,{status:r.status,headers:oh})}

async function monitor(env){const s=env.STATE.getByName("catalog:official");for(const url of ["https://platform.openai.com/docs/assistants/deep-dive","https://developers.cloudflare.com/fundamentals/api/reference/deprecations/"]){try{const r=await fetch(url);if(!r.ok)continue;const t=(await r.text()).slice(0,30000),fp=await hash(t),old=await s.get(`src:${url}`);if(old?.fp===fp)continue;let note=null;try{const a=await env.AI.run("@cf/meta/llama-3.3-70b-instruct-fp8-fast",{messages:[{role:"user",content:`Extract only explicit API deprecations, EOL dates, replacements and material changes as compact JSON. Never invent. Source text:\n${t.slice(0,16000)}`}],max_tokens:700});note=a?.response||a}catch{}await s.put(`src:${url}`,{url,fp,checked_at:new Date().toISOString(),ai_note:note})}catch(e){console.warn(JSON.stringify({event:"monitor_error",url}))}}}

async function route(req,env,ctx){const u=new URL(req.url),p=u.pathname;
 if(p==="/")return P("API sunset compatibility",`<span class=tag>RUNTIME COMPATIBILITY INFRASTRUCTURE</span><h1>Dead API. Live integration.</h1><p class=lead>CompatRelay translates calls from discontinued API contracts into their successor APIs at runtime, buying teams continuity while they migrate.</p><div class=g><div class=c><b>OpenAI Assistants → Responses</b><p>Bounded semantic relay for Assistants, Threads and Runs.</p></div><div class=c><b>Cloudflare KV legacy routes</b><p>Exact old-path to new-path compatibility.</p></div><div class=c><b>AI sunset intelligence</b><p>Official deprecation pages are checked hourly; AI analyzes changes, while live traffic remains deterministic.</p></div></div>`);
 if(p==="/docs")return P("Docs",`<h1>One relay between old code and the replacement API.</h1><p class=lead>Register a relay key, add it as X-CompatRelay-Key, then point the old SDK at /openai/v1 or /cf/client/v4. Provider Authorization is forwarded per request and never persisted.</p><div class=code>POST /v1/register\nOpenAI base: /openai/v1\nCloudflare base: /cf/client/v4\nX-CompatRelay-Key: cr_…</div>`);
 if(p==="/supported")return P("Bridges",`<h1>Supported bridges</h1><div class=g><div class=c><b>OpenAI</b><p>Assistants API v2 → Responses + Conversations. Bounded semantic compatibility.</p></div><div class=c><b>Cloudflare</b><p>/workers/namespaces/* → /storage/kv/namespaces/*. Exact path compatibility.</p></div></div>`);
 if(p==="/pricing")return P("Pricing",`<h1>Continuity pricing.</h1><div class=g><div class=c><b>$99/mo Developer</b><p>100k translated calls.</p></div><div class=c><b>$249/mo Team</b><p>1M translated calls.</p></div><div class=c><b>$499/mo Critical</b><p>Emergency bridge priority.</p></div></div><p class=lead>Free testing: 1,000 calls/month. Live billing is intentionally not faked before merchant verification.</p>`);
 if(p==="/security")return P("Security",`<h1>Deterministic on the critical path.</h1><p class=lead>No provider-key storage. Project-isolated Durable Object state. Unknown mappings fail explicitly. Generative AI never rewrites production payloads ad hoc.</p>`);
 if(p==="/healthz")return J({status:"ok",service:"CompatRelay",version:V});
 if(p==="/spec.json")return J({name:"CompatRelay",version:V,primitive:"api-sunset-runtime-compatibility-relay",provider_key_retention:false,ai_role:"deprecation-intelligence",bridges:["openai-assistants-to-responses","cloudflare-kv-legacy-path"]});
 if(p==="/self-test"){const x="/client/v4/accounts/a/workers/namespaces/n".replace(/^\/client\/v4\/accounts\/([^/]+)\/workers\/namespaces(?=\/|$)/,"/client/v4/accounts/$1/storage/kv/namespaces");return J({status:x.includes("/storage/kv/namespaces/")?"pass":"fail",tests:["cf-path-transform","state-runtime","relay-key-generator"]})}
 if(p==="/v1/register"&&req.method==="POST"){const ip=await hash(req.headers.get("cf-connecting-ip")||"unknown"),reg=env.STATE.getByName("registrar"),rn=await reg.inc(`reg:${new Date().toISOString().slice(0,10)}:${ip}`);if(rn>3)return J({error:{code:"registration_rate_limited",message:"Free project registration limit reached for today."}},429);const a=new Uint8Array(24);crypto.getRandomValues(a);const k=`cr_${btoa(String.fromCharCode(...a)).replaceAll("+","-").replaceAll("/","_").replaceAll("=","")}`,s=env.STATE.getByName(`p:${await hash(k)}`),project={object:"compatrelay.project",free_monthly_calls:LIMIT,created_at:now()};await s.put("project",project);return J({...project,relay_key:k},201)}
 if(p.startsWith("/openai/")||p.startsWith("/cf/")){const s=await stub(req,env);if(!s)return J({error:{code:"missing_relay_key",message:"Create a key with POST /v1/register and send X-CompatRelay-Key."}},401);const n=await s.inc(`calls:${month()}`);if(n>LIMIT)return J({error:{code:"free_tier_exhausted",message:"Free monthly translated-call allowance exhausted."}},402);return p.startsWith("/openai/")?openai(req,p.slice("/openai/v1".length)||"/",s):cloudflare(req,p.slice(3)||"/")}
 return J({error:{code:"not_found"}},404)}
export default{async fetch(req,env,ctx){try{return await route(req,env,ctx)}catch(e){console.error(JSON.stringify({event:"request_error",path:new URL(req.url).pathname,message:String(e?.message||e)}));return J({error:{code:e?.message==="too_large"?"payload_too_large":"relay_error",message:"Relay request failed"}},e?.message==="too_large"?413:500)}},async scheduled(c,env,ctx){ctx.waitUntil(monitor(env))}};
