import { DurableObject } from "cloudflare:workers";
import { ChangeMandateError, canonicalize, evaluateChange, sha256Hex } from "./core.mjs";

const SERVICE = "ChangeMandate";
const VERSION = "1.0.0";
const MAX_BODY_BYTES = 256 * 1024;
const JSON_HEADERS = { "content-type": "application/json; charset=utf-8", "cache-control": "no-store" };

function cors() { return { "access-control-allow-origin": "*", "access-control-allow-methods": "GET,POST,OPTIONS", "access-control-allow-headers": "content-type,authorization,x-request-id,x-change-nonce,payment-signature,payment" }; }
function json(data, status = 200, extra = {}) { return new Response(JSON.stringify(data), { status, headers: { ...JSON_HEADERS, ...cors(), ...extra } }); }
function err(code, message, status = 400, details = undefined) { return json({ error: { code, message, ...(details ? { details } : {}) } }, status); }
function safeEqual(a, b) { if (typeof a !== "string" || typeof b !== "string") return false; const x = new TextEncoder().encode(a), y = new TextEncoder().encode(b); if (x.length !== y.length) return false; let diff = 0; for (let i = 0; i < x.length; i++) diff |= x[i] ^ y[i]; return diff === 0; }
async function readJson(request) { const len = Number(request.headers.get("content-length") || 0); if (len > MAX_BODY_BYTES) throw new ChangeMandateError("PAYLOAD_TOO_LARGE", "Request body exceeds 256 KiB", 413); const text = await request.text(); if (new TextEncoder().encode(text).byteLength > MAX_BODY_BYTES) throw new ChangeMandateError("PAYLOAD_TOO_LARGE", "Request body exceeds 256 KiB", 413); try { return JSON.parse(text); } catch { throw new ChangeMandateError("INVALID_JSON", "Request body must be valid JSON", 400); } }
async function hmacSign(secret, value) { const key = await crypto.subtle.importKey("raw", new TextEncoder().encode(secret), { name: "HMAC", hash: "SHA-256" }, false, ["sign"]); const sig = await crypto.subtle.sign("HMAC", key, new TextEncoder().encode(value)); return [...new Uint8Array(sig)].map((b) => b.toString(16).padStart(2, "0")).join(""); }
async function decisionFor(body, env) { const result = await evaluateChange(body); const issuedAt = new Date().toISOString(); const decisionId = `cmd_${crypto.randomUUID()}`; const envelope = { ...result, decision_id: decisionId, issued_at: issuedAt }; if (env.DECISION_SIGNING_SECRET) { const canonical = canonicalize(envelope); envelope.signature = { alg: "HMAC-SHA256", value: await hmacSign(env.DECISION_SIGNING_SECRET, canonical) }; } else { envelope.signature = { alg: "none", value: null, mode: "developer" }; } return envelope; }
async function replayCheck(body, request, env) { const requestId = request.headers.get("x-request-id") || body.request_id; const nonce = request.headers.get("x-change-nonce") || body.nonce; if (!requestId || !nonce) throw new ChangeMandateError("IDEMPOTENCY_REQUIRED", "request_id and nonce are required (body or headers)", 400); if (String(requestId).length > 160 || String(nonce).length > 160) throw new ChangeMandateError("IDEMPOTENCY_INVALID", "request_id and nonce must be at most 160 characters", 400); const fingerprint = await sha256Hex({ request_id: String(requestId), nonce: String(nonce), original: body.original, proposed: body.proposed, operation: body.operation ?? null }); const shard = fingerprint.slice(0, 3); const stub = env.REPLAY_GUARD.getByName(shard); const claim = await stub.claim(String(requestId), String(nonce), fingerprint, 24 * 60 * 60 * 1000); if (claim.status === "conflict") throw new ChangeMandateError("REPLAY_CONFLICT", "The same request_id or nonce was reused with different content", 409); return { requestId: String(requestId), nonce: String(nonce), fingerprint, replay_status: claim.status }; }

export class ReplayGuard extends DurableObject {
  constructor(ctx, env) { super(ctx, env); this.ctx.storage.sql.exec(`CREATE TABLE IF NOT EXISTS claims (request_id TEXT NOT NULL, nonce TEXT NOT NULL, fingerprint TEXT NOT NULL, expires_at INTEGER NOT NULL, created_at INTEGER NOT NULL, PRIMARY KEY(request_id), UNIQUE(nonce))`); this.ctx.storage.sql.exec(`CREATE INDEX IF NOT EXISTS idx_claims_expiry ON claims(expires_at)`); }
  async claim(requestId, nonce, fingerprint, ttlMs) { const now = Date.now(); this.ctx.storage.sql.exec("DELETE FROM claims WHERE expires_at <= ?", now); const byRequest = this.ctx.storage.sql.exec("SELECT fingerprint, nonce FROM claims WHERE request_id = ?", requestId).toArray()[0]; if (byRequest) return { status: safeEqual(byRequest.fingerprint, fingerprint) && safeEqual(byRequest.nonce, nonce) ? "duplicate_same" : "conflict" }; const byNonce = this.ctx.storage.sql.exec("SELECT fingerprint, request_id FROM claims WHERE nonce = ?", nonce).toArray()[0]; if (byNonce) return { status: safeEqual(byNonce.fingerprint, fingerprint) && safeEqual(byNonce.request_id, requestId) ? "duplicate_same" : "conflict" }; this.ctx.storage.sql.exec("INSERT INTO claims(request_id, nonce, fingerprint, expires_at, created_at) VALUES (?, ?, ?, ?, ?)", requestId, nonce, fingerprint, now + ttlMs, now); return { status: "claimed" }; }
}

function pricing() { return { currency: "USD", model: "per_operation", tiers: [{ code: "basic_diff", price_usd: "0.002" }, { code: "monetary_delta_validation", price_usd: "0.005" }, { code: "authorization_issuance", price_usd: "0.010" }, { code: "recurring_liability_change", price_usd: "0.020" }, { code: "multi_merchant_change", price_usd: "0.030" }] }; }
function paymentMetadata(env) { const enabled = Boolean(env.PAY_TO && env.PAYMENTS_MODE === "x402"); return { enabled, mode: enabled ? "x402" : "developer", network: env.X402_NETWORK || "base", facilitator: env.X402_FACILITATOR || "https://x402.org/facilitator", note: enabled ? "Payment verification is required for paid endpoints." : "Payments are not enabled because no recipient wallet is configured." }; }
function openapi(origin) { return { openapi: "3.1.0", info: { title: "ChangeMandate API", version: VERSION, description: "Authorization-diff primitive for post-purchase changes in agentic commerce." }, servers: [{ url: origin }], paths: { "/v1/authorize-order-change": { post: { operationId: "authorizeOrderChange", summary: "Evaluate whether a post-purchase modification is covered by the original authorization", parameters: [{ in: "header", name: "X-Request-Id", required: true, schema: { type: "string" } }, { in: "header", name: "X-Change-Nonce", required: true, schema: { type: "string" } }], requestBody: { required: true, content: { "application/json": { schema: { type: "object", required: ["original", "proposed"] } } } }, responses: { "200": { description: "Deterministic authorization-diff decision" }, "409": { description: "Replay conflict" } } } }, "/healthz": { get: { responses: { "200": { description: "Healthy" } } } }, "/pricing": { get: { responses: { "200": { description: "Per-operation prices" } } } } } }; }
function mcpTools() { return [{ name: "authorize_order_change", description: "Compare an original authorized commerce transaction with a proposed post-purchase modification and decide whether new authorization is required.", inputSchema: { type: "object", required: ["request_id", "nonce", "original", "proposed"], properties: { request_id: { type: "string" }, nonce: { type: "string" }, original: { type: "object" }, proposed: { type: "object" }, operation: { type: "object" } } } }]; }
async function mcp(request, env) { const msg = await readJson(request); const id = msg.id ?? null; if (msg.jsonrpc !== "2.0" || typeof msg.method !== "string") return json({ jsonrpc: "2.0", id, error: { code: -32600, message: "Invalid Request" } }, 400); if (msg.method === "initialize") return json({ jsonrpc: "2.0", id, result: { protocolVersion: "2025-11-25", capabilities: { tools: {} }, serverInfo: { name: SERVICE, version: VERSION } } }); if (msg.method === "notifications/initialized") return new Response(null, { status: 202, headers: cors() }); if (msg.method === "tools/list") return json({ jsonrpc: "2.0", id, result: { tools: mcpTools() } }); if (msg.method === "tools/call") { if (msg.params?.name !== "authorize_order_change") return json({ jsonrpc: "2.0", id, error: { code: -32602, message: "Unknown tool" } }, 400); try { const args = msg.params?.arguments ?? {}; const fakeRequest = new Request(request.url, { method: "POST", headers: { "x-request-id": args.request_id || "", "x-change-nonce": args.nonce || "" } }); const replay = await replayCheck(args, fakeRequest, env); const result = await decisionFor(args, env); return json({ jsonrpc: "2.0", id, result: { content: [{ type: "text", text: `${result.decision}: ${result.explanation}` }], structuredContent: { ...result, idempotency: replay } } }); } catch (e) { const message = e instanceof Error ? e.message : "Tool call failed"; return json({ jsonrpc: "2.0", id, result: { isError: true, content: [{ type: "text", text: message }] } }, e?.status || 400); } } return json({ jsonrpc: "2.0", id, error: { code: -32601, message: "Method not found" } }, 404); }

function landing(origin, payments) { const badge = payments.enabled ? "x402 payments enabled" : "developer mode"; return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>ChangeMandate — authorize the delta, not the whole transaction</title><meta name="description" content="A deterministic authorization-diff API for post-purchase changes made by AI agents."><style>:root{color-scheme:dark light;font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}body{margin:0;background:#0a0b0d;color:#f5f7fa}main{max-width:980px;margin:auto;padding:72px 24px 96px}nav{display:flex;justify-content:space-between;align-items:center;margin-bottom:84px}.mark{font-weight:780;letter-spacing:-.03em}.pill{font-size:12px;border:1px solid #2a2e35;border-radius:999px;padding:7px 10px;color:#aab1bb}h1{font-size:clamp(44px,8vw,86px);line-height:.94;letter-spacing:-.065em;margin:0;max-width:900px}p.lead{font-size:20px;line-height:1.55;color:#aab1bb;max-width:690px;margin:30px 0 44px}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin:48px 0}.card{border:1px solid #22262d;background:#101216;border-radius:18px;padding:22px}.card b{display:block;font-size:26px;margin-bottom:8px}.card span{color:#9ca3af;font-size:14px;line-height:1.5}pre{overflow:auto;background:#101216;border:1px solid #22262d;border-radius:18px;padding:22px;color:#d7dde6}.links{display:flex;gap:10px;flex-wrap:wrap}.links a{color:#fff;text-decoration:none;border:1px solid #343a43;border-radius:10px;padding:11px 14px}footer{margin-top:72px;color:#737b87;font-size:13px}@media(max-width:720px){.grid{grid-template-columns:1fr}nav{margin-bottom:54px}}</style></head><body><main><nav><div class="mark">ChangeMandate</div><div class="pill">${badge}</div></nav><h1>Authorize the change.<br>Not the whole transaction.</h1><p class="lead">AI agents can modify completed orders. ChangeMandate computes the economic and contractual delta, then returns a deterministic decision: ALLOW, ALLOW_WITHIN_PREAUTHORIZED_DELTA, or NEW_AUTHORIZATION_REQUIRED.</p><div class="links"><a href="/docs">API docs</a><a href="/openapi.json">OpenAPI</a><a href="/pricing">Pricing</a><a href="/status">Status</a></div><div class="grid"><div class="card"><b>$0.002</b><span>Basic authorization diff</span></div><div class="card"><b>$0.005</b><span>Monetary delta validation</span></div><div class="card"><b>$0.02</b><span>Recurring liability change</span></div></div><pre>POST ${origin}/v1/authorize-order-change\n\nRetail exchange · flight change · hotel upgrade · delivery substitute · subscription upgrade</pre><footer>ChangeMandate is an authorization decision aid and protocol service. It is not a bank, payment processor, merchant of record, or legal advisor.</footer></main></body></html>`; }
function docs(origin) { const example = { request_id: "req_demo_001", nonce: "nonce_demo_001", operation: { type: "exchange" }, original: { order_id: "order_1001", checkout_hash: "sha256:original-checkout", merchant_id: "merchant_store", currency: "USD", one_time_total_minor: 10000, recurring: [], line_items: [{ id: "shoe-42", quantity: 1, unit_price_minor: 10000 }], authorization: { max_additional_one_time_minor: 2500, allow_recurring: false, max_recurring_delta_minor: 0, allowed_merchants: ["merchant_store"], allow_currency_change: false, allow_multi_merchant: false, allow_quantity_increase: false } }, proposed: { merchant_id: "merchant_store", currency: "USD", one_time_total_minor: 11700, recurring: [], line_items: [{ id: "shoe-43", quantity: 1, unit_price_minor: 11700 }] } }; return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>ChangeMandate Docs</title><style>body{font:15px/1.6 ui-monospace,SFMono-Regular,Menlo,monospace;background:#0b0d10;color:#e8ebef;max-width:900px;margin:auto;padding:48px 22px}a{color:#9fc2ff}pre,textarea{box-sizing:border-box;width:100%;background:#11151b;color:#dfe7f2;border:1px solid #29313d;border-radius:12px;padding:16px;overflow:auto}textarea{min-height:420px}button{background:#fff;color:#000;border:0;border-radius:10px;padding:10px 16px;font-weight:700;cursor:pointer}#out{min-height:120px}</style></head><body><p><a href="/">← ChangeMandate</a></p><h1>API Playground</h1><p>POST <code>/v1/authorize-order-change</code>. Every request requires a unique request_id and nonce. Decisions are deterministic; an LLM is never used for authorization.</p><textarea id="body">${JSON.stringify(example, null, 2).replaceAll("<", "&lt;")}</textarea><p><button id="run">Evaluate change</button></p><pre id="out">Ready.</pre><h2>MCP</h2><p>Connect to <code>${origin}/mcp</code> and call <code>authorize_order_change</code>.</p><h2>Machine discovery</h2><p><a href="/.well-known/changemandate">/.well-known/changemandate</a> · <a href="/.well-known/x402">/.well-known/x402</a> · <a href="/openapi.json">/openapi.json</a></p><script>document.getElementById('run').onclick=async()=>{const out=document.getElementById('out');out.textContent='Running…';try{const b=JSON.parse(document.getElementById('body').value);const r=await fetch('/v1/authorize-order-change',{method:'POST',headers:{'content-type':'application/json','x-request-id':b.request_id,'x-change-nonce':b.nonce},body:JSON.stringify(b)});out.textContent=JSON.stringify(await r.json(),null,2)}catch(e){out.textContent=String(e)}}</script></body></html>`; }

async function route(request, env) { if (request.method === "OPTIONS") return new Response(null, { status: 204, headers: cors() }); const url = new URL(request.url); const origin = url.origin; const payments = paymentMetadata(env); if (request.method === "GET" && url.pathname === "/") return new Response(landing(origin, payments), { headers: { "content-type": "text/html; charset=utf-8", ...cors() } }); if (request.method === "GET" && url.pathname === "/docs") return new Response(docs(origin), { headers: { "content-type": "text/html; charset=utf-8", ...cors() } }); if (request.method === "GET" && url.pathname === "/healthz") return json({ status: "ok", service: SERVICE, version: VERSION }); if (request.method === "GET" && url.pathname === "/status") return json({ status: "operational", service: SERVICE, version: VERSION, payments }); if (request.method === "GET" && url.pathname === "/pricing") return json(pricing()); if (request.method === "GET" && url.pathname === "/openapi.json") return json(openapi(origin)); if (request.method === "GET" && url.pathname === "/.well-known/changemandate") return json({ name: SERVICE, version: VERSION, primitive: "post-purchase-authorization-diff", endpoint: `${origin}/v1/authorize-order-change`, mcp: `${origin}/mcp`, openapi: `${origin}/openapi.json`, pricing: pricing(), payments }); if (request.method === "GET" && url.pathname === "/.well-known/x402") return json({ x402Version: 2, resource: `${origin}/v1/authorize-order-change`, payments, pricing: pricing(), note: "Payment enforcement is activated only when PAYMENTS_MODE=x402 and PAY_TO is configured." }); if (request.method === "GET" && url.pathname === "/server.json") return json({ $schema: "https://static.modelcontextprotocol.io/schemas/2025-12-11/server.schema.json", name: "io.changemandate/server", description: "Authorization-diff primitive for post-purchase changes in agentic commerce", version: VERSION, remotes: [{ type: "streamable-http", url: `${origin}/mcp` }] }); if (request.method === "POST" && url.pathname === "/mcp") return mcp(request, env); if (request.method === "POST" && url.pathname === "/v1/authorize-order-change") { try { const body = await readJson(request); const replay = await replayCheck(body, request, env); const result = await decisionFor(body, env); return json({ ...result, idempotency: replay, payment: payments }); } catch (e) { if (e instanceof ChangeMandateError) return err(e.code, e.message, e.status); console.error(JSON.stringify({ level: "error", service: SERVICE, error: e instanceof Error ? e.message : String(e) })); return err("INTERNAL_ERROR", "Unexpected error", 500); } } return err("NOT_FOUND", "Route not found", 404); }

export default { fetch: route };
