export const SCHEMA_VERSION = 2;
// Additive migration only. Historical observations, changes and evidence are immutable.
export const SCHEMA = [
  `CREATE TABLE IF NOT EXISTS schema_versions(version INTEGER PRIMARY KEY, applied_at TEXT NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS entities(id TEXT PRIMARY KEY, title TEXT NOT NULL, topic TEXT NOT NULL, published INTEGER NOT NULL DEFAULT 0, suppressed INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL, updated_at TEXT NOT NULL)`,
  `CREATE INDEX IF NOT EXISTS entity_topic ON entities(topic,published,suppressed,id)`,
  `CREATE TABLE IF NOT EXISTS topics(id TEXT PRIMARY KEY, title TEXT NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS sources(id TEXT PRIMARY KEY, spec_json TEXT NOT NULL, domain TEXT NOT NULL, enabled INTEGER NOT NULL DEFAULT 1, etag TEXT, last_modified TEXT, last_hash TEXT, last_success TEXT, next_fetch INTEGER NOT NULL DEFAULT 0, failures INTEGER NOT NULL DEFAULT 0, last_error TEXT, lease_until INTEGER NOT NULL DEFAULT 0, last_interval INTEGER NOT NULL DEFAULT 86400)`,
  `CREATE INDEX IF NOT EXISTS source_due ON sources(enabled,next_fetch,lease_until)`,
  `CREATE TABLE IF NOT EXISTS source_reliability(source_id TEXT PRIMARY KEY, successes INTEGER NOT NULL DEFAULT 0, failures INTEGER NOT NULL DEFAULT 0, changes INTEGER NOT NULL DEFAULT 0)`,
  `CREATE TABLE IF NOT EXISTS fact_definitions(id TEXT PRIMARY KEY, entity_id TEXT NOT NULL REFERENCES entities(id), fact_key TEXT NOT NULL, label TEXT NOT NULL, value_type TEXT NOT NULL, unit TEXT, max_age INTEGER NOT NULL, UNIQUE(entity_id,fact_key))`,
  `CREATE TABLE IF NOT EXISTS source_fetches(id TEXT PRIMARY KEY, source_id TEXT NOT NULL, observed_at TEXT NOT NULL, http_status INTEGER, latency_ms INTEGER, bytes INTEGER, source_hash TEXT, error TEXT, method TEXT NOT NULL)`,
  `CREATE INDEX IF NOT EXISTS fetch_source_time ON source_fetches(source_id,observed_at DESC)`,
  `CREATE INDEX IF NOT EXISTS fetch_time ON source_fetches(observed_at)`,
  `CREATE TABLE IF NOT EXISTS evidence(id TEXT PRIMARY KEY, source_hash TEXT NOT NULL, source_url TEXT NOT NULL, source_domain TEXT NOT NULL, source_type TEXT NOT NULL, retrieved_at TEXT NOT NULL, method TEXT NOT NULL, fetch_id TEXT NOT NULL, normalized_json TEXT NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS fact_observations(id TEXT PRIMARY KEY, fact_id TEXT NOT NULL REFERENCES fact_definitions(id), value_json TEXT NOT NULL, observed_at TEXT NOT NULL, valid_from TEXT NOT NULL, verification TEXT NOT NULL, evidence_id TEXT NOT NULL REFERENCES evidence(id))`,
  `CREATE INDEX IF NOT EXISTS observation_history ON fact_observations(fact_id,observed_at DESC,id)`,
  `CREATE TABLE IF NOT EXISTS current_facts(id TEXT PRIMARY KEY REFERENCES fact_definitions(id), observation_id TEXT NOT NULL REFERENCES fact_observations(id), value_json TEXT NOT NULL, previous_json TEXT, verified_at TEXT NOT NULL, changed_at TEXT NOT NULL, change_type TEXT NOT NULL, verification TEXT NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS fact_changes(id TEXT PRIMARY KEY, fact_id TEXT NOT NULL REFERENCES fact_definitions(id), entity_id TEXT NOT NULL, previous_json TEXT, value_json TEXT NOT NULL, observed_at TEXT NOT NULL, change_type TEXT NOT NULL, observation_id TEXT NOT NULL REFERENCES fact_observations(id))`,
  `CREATE INDEX IF NOT EXISTS change_time ON fact_changes(observed_at DESC,id)`,
  `CREATE INDEX IF NOT EXISTS change_entity ON fact_changes(entity_id,observed_at DESC,id)`,
  `CREATE TABLE IF NOT EXISTS entity_relationships(parent_id TEXT NOT NULL, related_id TEXT NOT NULL, relation TEXT NOT NULL, PRIMARY KEY(parent_id,related_id,relation))`,
  `CREATE TABLE IF NOT EXISTS discovery_candidates(id TEXT PRIMARY KEY, spec_json TEXT NOT NULL, provenance TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'pending', created_at TEXT NOT NULL, error TEXT)`,
  `CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value TEXT NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS domain_leases(domain TEXT PRIMARY KEY, token TEXT NOT NULL, until_ms INTEGER NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS robots(domain TEXT PRIMARY KEY, body TEXT NOT NULL, checked_at INTEGER NOT NULL, status INTEGER NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS crawler_requests(id TEXT PRIMARY KEY, timestamp TEXT NOT NULL, path TEXT NOT NULL, status INTEGER NOT NULL, content_type TEXT, cache TEXT, classification TEXT NOT NULL, operator TEXT, user_agent TEXT, referrer TEXT, country TEXT, bytes INTEGER, latency_ms REAL, visitor_hash TEXT, synthetic INTEGER NOT NULL DEFAULT 0)`,
  `CREATE INDEX IF NOT EXISTS request_time ON crawler_requests(timestamp)`,
  `CREATE TABLE IF NOT EXISTS request_metrics(day TEXT NOT NULL,path TEXT NOT NULL,operator TEXT NOT NULL,classification TEXT NOT NULL,status INTEGER NOT NULL,cache TEXT NOT NULL,requests INTEGER NOT NULL,bytes INTEGER NOT NULL,latency_ms REAL NOT NULL,PRIMARY KEY(day,path,operator,classification,status,cache))`,
  `CREATE TABLE IF NOT EXISTS crawler_visitors(day TEXT NOT NULL,visitor_hash TEXT NOT NULL,operator TEXT NOT NULL,requests INTEGER NOT NULL,PRIMARY KEY(day,visitor_hash,operator))`,
  `CREATE TABLE IF NOT EXISTS ai_referrals(day TEXT NOT NULL,path TEXT NOT NULL,platform TEXT NOT NULL,requests INTEGER NOT NULL,PRIMARY KEY(day,path,platform))`,
  `CREATE TABLE IF NOT EXISTS monetization_events(id TEXT PRIMARY KEY, external_id TEXT NOT NULL, program TEXT NOT NULL CHECK(program IN ('pay-per-crawl','pay-per-use')), buyer TEXT NOT NULL, path TEXT NOT NULL, occurred_at TEXT NOT NULL, amount_micros INTEGER NOT NULL CHECK(amount_micros>=0), currency TEXT NOT NULL CHECK(currency='USD'), uses INTEGER NOT NULL CHECK(uses>0), report_hash TEXT NOT NULL, report_reference TEXT NOT NULL, imported_at TEXT NOT NULL, UNIQUE(program,external_id))`,
  `CREATE TABLE IF NOT EXISTS corrections(id TEXT PRIMARY KEY, fact_id TEXT NOT NULL, message TEXT NOT NULL, source_url TEXT NOT NULL, created_at TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'pending', resolution TEXT)`,
  `CREATE TABLE IF NOT EXISTS audit_log(id TEXT PRIMARY KEY, timestamp TEXT NOT NULL, actor TEXT NOT NULL, action TEXT NOT NULL, detail_json TEXT NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS costs(month TEXT PRIMARY KEY, amount_micros INTEGER NOT NULL CHECK(amount_micros>=0), reference TEXT NOT NULL, recorded_at TEXT NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS rate_limits(key TEXT PRIMARY KEY,count INTEGER NOT NULL,expires INTEGER NOT NULL)`,
  ...['fact_observations', 'fact_changes', 'evidence', 'monetization_events', 'audit_log'].flatMap(table => ['UPDATE', 'DELETE'].map(action =>
    `CREATE TRIGGER IF NOT EXISTS immutable_${table}_${action.toLowerCase()} BEFORE ${action} ON ${table} BEGIN SELECT RAISE(ABORT,'immutable_history'); END`)),
];
